# This is a basic workflow to help you get started with iCR CI/CD
# Suppouse your github enterprise url is github.openrefactory.com
name: Openrefactory_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    
env:
  REGISTRY: ghcr.io
  #REGISTRY: docker.github.openrefactory.com #use this line if you are using github enterprise

jobs:
  OR_JOB:
    runs-on: ubuntu-18.04 # Or you can use ubuntu-latest
    #runs-on: self-hosted #if you are using github enterprise please mention your runner name
    container:
            image: ghcr.io/User_ID/icr-github:latest
            #image: docker.ge.openrefactory.com/User_ID/Project_Name/icr-github:latest #for github enterprise image name will be here
            
    steps:
      - uses: actions/checkout@v2 # comment this line if you are using github enterprise
      - name: orjob
        run: |
          /workspace/configure_run.sh ${{ github.ref_name }} \
          ${{ github.repositoryUrl }} \
          ${{ secrets.ICR_URL }} \
          ${{ secrets.ICR_PASSPHRASE }} \
          ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
          ${{ secrets.MAIL_ADDRESS }} \
          ${{ secrets.LANGUAGE_VERSION }} 
        shell: bash
